# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2021

obj-$(CONFIG_NAND_MTK_DTV) += drvNAND.o
obj-$(CONFIG_NAND_MTK_DTV) += drvNAND_hal_v5.o
obj-$(CONFIG_NAND_MTK_DTV) += drvNAND_platform.o
obj-$(CONFIG_NAND_MTK_DTV) += drvNAND_utl.o
obj-$(CONFIG_NAND_MTK_DTV) += mtk-dtv-nand.o