# SPDX-License-Identifier: (GPL-2.0-only OR BSD-3-Clause)
#
# Copyright (c) 2023 MediaTek Inc.
#

UBOOTINCLUDE += -I$(srctree)/lib/libufdt/include/ \
                -I$(srctree)/Mediatek-internal/include/

obj-y += ./mtk_dtbo.o
