// SPDX-License-Identifier: GPL-2.0+
/*
 * Copyright (C) 2017 Google, Inc
 * Written by Simon Glass <sjg@chromium.org>
 */

#include <common.h>
#include <environment.h>
#include <utility.h>
#include <generated/cusdefaultenv_autogenerated.h>
#include <generated/bootcommands_autogenerated.h>
#ifdef CONFIG_MULTICORES_PLATFORM
#include <smp/thread_info.h>
extern smp_spin_lock_t env_lock;
#endif

#if defined(UFBL_FEATURE_IDME)
#include <idme.h>
#endif

#define UENV_PARTITION          "uenv"
#define UENV_RELOAD             "uenv_reload"
#define UENV_RELOAD_FILE_NAME   "/uenv_reload"

DECLARE_GLOBAL_DATA_PTR;

#if defined(CONFIG_NEEDS_MANUAL_RELOC)
void env_fix_drivers(void)
{
	struct env_driver *drv;
	const int n_ents = ll_entry_count(struct env_driver, env_driver);
	struct env_driver *entry;

	drv = ll_entry_start(struct env_driver, env_driver);
	for (entry = drv; entry != drv + n_ents; entry++) {
		if (entry->name)
			entry->name += gd->reloc_off;
		if (entry->load)
			entry->load += gd->reloc_off;
		if (entry->save)
			entry->save += gd->reloc_off;
		if (entry->init)
			entry->init += gd->reloc_off;
	}
}
#endif

static struct env_driver *_env_driver_lookup(enum env_location loc)
{
	struct env_driver *drv;
	const int n_ents = ll_entry_count(struct env_driver, env_driver);
	struct env_driver *entry;

	drv = ll_entry_start(struct env_driver, env_driver);
	for (entry = drv; entry != drv + n_ents; entry++) {
		if (loc == entry->location)
			return entry;
	}

	/* Not found */
	return NULL;
}

static enum env_location env_locations[] = {
#ifdef CONFIG_ENV_IS_IN_EEPROM
	ENVL_EEPROM,
#endif
#ifdef CONFIG_ENV_IS_IN_EXT4
	ENVL_EXT4,
#endif
#ifdef CONFIG_ENV_IS_IN_CUST_EXT4
	ENVL_CUST_EXT4,
#endif
#ifdef CONFIG_ENV_IS_IN_FAT
	ENVL_FAT,
#endif
#ifdef CONFIG_ENV_IS_IN_FLASH
	ENVL_FLASH,
#endif
#ifdef CONFIG_ENV_IS_IN_MMC
	ENVL_MMC,
#endif
#ifdef CONFIG_ENV_IS_IN_UFS
	ENVL_UFS,
#endif
#ifdef CONFIG_ENV_IS_IN_NAND
	ENVL_NAND,
#endif
#ifdef CONFIG_ENV_IS_IN_NVRAM
	ENVL_NVRAM,
#endif
#ifdef CONFIG_ENV_IS_IN_REMOTE
	ENVL_REMOTE,
#endif
#ifdef CONFIG_ENV_IS_IN_SATA
	ENVL_ESATA,
#endif
#ifdef CONFIG_ENV_IS_IN_SPI_FLASH
	ENVL_SPI_FLASH,
#endif
#ifdef CONFIG_ENV_IS_IN_UBI
	ENVL_UBI,
#endif
#ifdef CONFIG_ENV_IS_NOWHERE
	ENVL_NOWHERE,
#endif
};

static bool env_has_inited(enum env_location location)
{
	return gd->env_has_init & BIT(location);
}

static void env_set_inited(enum env_location location)
{
	/*
	 * We're using a 32-bits bitmask stored in gd (env_has_init)
	 * using the above enum value as the bit index. We need to
	 * make sure that we're not overflowing it.
	 */
	BUILD_BUG_ON(ARRAY_SIZE(env_locations) > BITS_PER_LONG);

	gd->env_has_init |= BIT(location);
}

/**
 * env_get_location() - Returns the best env location for a board
 * @op: operations performed on the environment
 * @prio: priority between the multiple environments, 0 being the
 *        highest priority
 *
 * This will return the preferred environment for the given priority.
 * This is overridable by boards if they need to.
 *
 * All implementations are free to use the operation, the priority and
 * any other data relevant to their choice, but must take into account
 * the fact that the lowest prority (0) is the most important location
 * in the system. The following locations should be returned by order
 * of descending priorities, from the highest to the lowest priority.
 *
 * Returns:
 * an enum env_location value on success, a negative error code otherwise
 */
__weak enum env_location env_get_location(enum env_operation op, int prio)
{
	if (prio >= ARRAY_SIZE(env_locations))
		return ENVL_UNKNOWN;

	gd->env_load_prio = prio;

	return env_locations[prio];
}


/**
 * env_driver_lookup() - Finds the most suited environment location
 * @op: operations performed on the environment
 * @prio: priority between the multiple environments, 0 being the
 *        highest priority
 *
 * This will try to find the available environment with the highest
 * priority in the system.
 *
 * Returns:
 * NULL on error, a pointer to a struct env_driver otherwise
 */
static struct env_driver *env_driver_lookup(enum env_operation op, int prio)
{
	enum env_location loc = env_get_location(op, prio);
	struct env_driver *drv;

	if (loc == ENVL_UNKNOWN)
		return NULL;

	drv = _env_driver_lookup(loc);
	if (!drv) {
		debug("%s: No environment driver for location %d\n", __func__,
		      loc);
		return NULL;
	}

	return drv;
}

__weak int env_get_char_spec(int index)
{
	return *(uchar *)(gd->env_addr + index);
}

int env_get_char(int index)
{
	if (gd->env_valid == ENV_INVALID)
		return default_environment[index];
	else
		return env_get_char_spec(index);
}

#define STRING_MAX_LENGTH 1024
/*Append backslash avoid bootcmd being cut*/
int env_append_backslash(char* cmd_in, char* cmd_out)
{
	int i=0, count=1, start1=0, start2=0;
	int len = strlen(cmd_in);
	char cmd[STRING_MAX_LENGTH] = "";
	char* cat = {"\\"};

	if(len > STRING_MAX_LENGTH)
		len = STRING_MAX_LENGTH;

	while(i < len)
	{
		if(*(cmd_in+i) == ';')
		{
			memcpy(cmd+start1, cmd_in+start2, i-start2);
			cmd[start1 + i-start2] = '\0';
			strncat(cmd, cat, strlen(cat));
			start1 = i + count;
			start2 = i;
			count++;
		}
		else if(i == strlen(cmd_in)-1)
		{
			memcpy(cmd+start1, cmd_in+start2, i-start2+1);
		}
		i++;
	}
	memset(cmd_out, '\0', STRING_MAX_LENGTH);
	memcpy(cmd_out, cmd, strlen(cmd));

	return 0;
}

int env_cus_load(void)
{
	char* env_cmd = "";
	char env_cmd_temp[STRING_MAX_LENGTH] = "";
	const char* dtb_sel_file_default = UBOOT_ENV_DTBO_SEL;
	const char* ubootmodel = UBOOT_MODEL_NAME;
	#if defined(UFBL_FEATURE_IDME)
	char model_name[128] = "\0";
	char config_name[128] = "\0";
	#endif
	bool use_default_dtbo = 1;
	bool use_default_dataindex = 1;
	int ret = 0;

	run_command("env default -a", 0);

	run_command("setenv bootargs console=ttyS0,115200 androidboot.console=ttyS0 init=/init CORE_DUMP_PATH=/data/core_dump.%%p.gz KDebug=1 delaylogo=true security=selinux SD_CONFIG=2 loop.max_part=7 \
			vmpressure_level_critical=80 cgroup.memory=nokmem utpa_str_fr=1 8250.nr_uarts=4 vmalloc=550M kasan_multi_shot=1 transparent_hugepage=never firmware_class.path=/vendor/tvconfig/,/vendor/firmware/", 0);
	run_command("setenv verify n", 0);
	run_command("setenv devicestate unlock", 0);
	run_command("avb set-devicestate 0", 0);
	run_command("setenv usb_auto_upgrade disable", 0);
	run_command("setenv force_boot_recovery false", 0);
	run_command("setenv autoload 0", 0);
	run_command("setenv android_manufacturer Mediatek", 0);
	run_command("setenv dtbo_cfg_part bootdata", 0);
	run_command("setenv dataindex_cfg_name default", 0);
	run_command("setenv bootconfig 0", 0);

	run_command("setenv initrd_high 0x2B000000", 0);
	run_command("setenv fdt_high 0x2B800000", 0);
	run_command("setenv dtboaddr 0x2C000000", 0);

	env_cmd = malloc(STRING_MAX_LENGTH);
	if(env_cmd)
	{
		ret = snprintf(env_cmd, STRING_MAX_LENGTH, "setenv android_product %s; setenv board %s", ubootmodel, ubootmodel);
		if(ret < 0)
			return -ENODEV;
		run_command(env_cmd, 0);

		// load dtbo_cfg_sel from idme model_name
		#if defined(UFBL_FEATURE_IDME)
		idme_get_var_external("model_name", model_name, (127));
		printf("model_name = %s\n", model_name);
		if (!strcmp(model_name, "0") || !strcmp(model_name, "") || !strcmp(model_name, "/config/model/Customer_1.ini"))
		{
			printf("model_name is invalid, use default one\n");
			use_default_dtbo = 1;
		}
		else
			use_default_dtbo = 0;
		#endif
		if ( use_default_dtbo == 0)
		{
			printf("update dtbo_cfg_sel based on model name in idme %s \n", model_name);
			ret = snprintf(env_cmd, STRING_MAX_LENGTH, "setenv dtbo_cfg_sel dtb/%s", model_name);
		} 
		else
		{
			ret = snprintf(env_cmd, STRING_MAX_LENGTH, "setenv dtbo_cfg_sel dtb/%s", dtb_sel_file_default);
		}
		if(ret < 0)
			return -ENODEV;
		run_command(env_cmd, 0);

		// load dataindex_cfg_name from idme config_name
		#if defined(UFBL_FEATURE_IDME)
		idme_get_var_external("config_name", config_name, (127));
		printf("config_name = %s\n", config_name);
		if (!strcmp(config_name, "0") || !strcmp(config_name, ""))
		{
			printf("config_name is invalid, use default one\n");
			use_default_dataindex = 1;
		}
		else
			use_default_dataindex = 0;
		#endif
		if ( use_default_dataindex == 0)
		{
			printf("update dataindex_cfg_name based on config_name in idme %s \n", config_name);
			ret = snprintf(env_cmd, STRING_MAX_LENGTH, "setenv dataindex_cfg_name %s", config_name);
		}
		else
		{
			ret = snprintf(env_cmd, STRING_MAX_LENGTH, "setenv dataindex_cfg_name default");
		}
		if(ret < 0)
			return -ENODEV;
		run_command(env_cmd, 0);

		ret = snprintf(env_cmd_temp, STRING_MAX_LENGTH, "setenv bootcmd %s", UBOOT_BOOTCMD);
		if(ret < 0)
			return -ENODEV;
		env_append_backslash(env_cmd_temp, env_cmd);
		run_command(env_cmd, 0);
		ret = snprintf(env_cmd_temp, STRING_MAX_LENGTH, "setenv recoverycmd %s", UBOOT_REVOCERYCMD);
		if(ret < 0)
			return -ENODEV;
		env_append_backslash(env_cmd_temp, env_cmd);
		run_command(env_cmd, 0);
		free(env_cmd);
	}
	else
	{
		printf("%s env_cmd malloc fail\n", __func__);
	}
	run_command("saveenv", 0);

	return 0;
}

int do_env_cus_load(cmd_tbl_t *cmdtp, int flag, int argc, char * const argv[])
{
	return env_cus_load();
}

int env_load(void)
{
	struct env_driver *drv;
	int best_prio = -1;
	int prio;
	unsigned char *rd_buf = NULL;
	unsigned char wr_buf[] = "0";
	loff_t rd_size;
	loff_t wr_size = 1;

	for (prio = 0; (drv = env_driver_lookup(ENVOP_LOAD, prio)); prio++) {
		int ret;

		if (!drv->load)
			continue;

		if (!env_has_inited(drv->location))
			continue;

		printf("Loading Environment from %s... ", drv->name);
		/*
		 * In error case, the error message must be printed during
		 * drv->load() in some underlying API, and it must be exactly
		 * one message.
		 */
		ret = drv->load();
		if (!ret) {
			printf("OK\n");
			return 0;
		} else if (ret == -ENOMSG) {
			/* Handle "bad CRC" case */
			if (best_prio == -1)
				best_prio = prio;
		} else {
			/* handle after successful ota installation */
			rd_buf = read_storage_file_to_memory(UENV_PARTITION, UENV_RELOAD, &rd_size);
			if (rd_buf && (strncmp((const char*)rd_buf, "1", 1) == 0)) {
				printf("Reload uenv after ota\n");
				env_cus_load();

				/* unset uenv_reload flag */
				if (write_storage_file(UENV_PARTITION, UENV_RELOAD_FILE_NAME,
						wr_buf, &wr_size) == NULL) {
					printf("Write uenv_reload failed \n");
				}
			} else {
				/* handle for first bootup*/
				printf("Format uenv partition to EXT4\n");
				run_command("formatenv mmc 0", 0);
				env_cus_load();
				ret = drv->load();
				if (!ret) {
					printf("OK\n");
					return 0;
				} else if (ret == -ENOMSG) {
					/* Handle "bad CRC" case */
					if (best_prio == -1)
						best_prio = prio;
				} else {
					debug("Failed (%d)\n", ret);
				}
			}

			/* delete read buf */
			if (rd_buf) {
				free(rd_buf);
			}
		}
	}

	/*
	 * In case of invalid environment, we set the 'default' env location
	 * to the best choice, i.e.:
	 *   1. Environment location with bad CRC, if such location was found
	 *   2. Otherwise use the location with highest priority
	 *
	 * This way, next calls to env_save() will restore the environment
	 * at the right place.
	 */
	if (best_prio >= 0)
		debug("Selecting environment with bad CRC\n");
	else
		best_prio = 0;
	env_get_location(ENVOP_LOAD, best_prio);

	return -ENODEV;
}

int env_save(void)
{
	struct env_driver *drv;
#ifdef CONFIG_MULTICORES_PLATFORM
	unsigned long irq_flag = 0;
#endif

	drv = env_driver_lookup(ENVOP_SAVE, gd->env_load_prio);
	if (drv) {
		int ret;

		if (!drv->save)
			return -ENODEV;

		if (!env_has_inited(drv->location))
			return -ENODEV;

		printf("Saving Environment to %s... ", drv->name);
#ifdef CONFIG_MULTICORES_PLATFORM
		smp_spin_lock_save(&env_lock, irq_flag);
#endif
		ret = drv->save();
#ifdef CONFIG_MULTICORES_PLATFORM
		smp_spin_unlock_restore(&env_lock, irq_flag);
#endif
		if (ret)
			printf("Failed (%d)\n", ret);
		else
			printf("OK\n");

		if (!ret)
			return 0;
	}

	return -ENODEV;
}

int env_init(void)
{
	struct env_driver *drv;
	int ret = -ENOENT;
	int prio;

	for (prio = 0; (drv = env_driver_lookup(ENVOP_INIT, prio)); prio++) {
		if (!drv->init || !(ret = drv->init()))
			env_set_inited(drv->location);

		debug("%s: Environment %s init done (ret=%d)\n", __func__,
		      drv->name, ret);
	}

	if (!prio)
		return -ENODEV;

	if (ret == -ENOENT) {
		gd->env_addr = (ulong)&default_environment[0];
		gd->env_valid = ENV_VALID;

		return 0;
	}

	return ret;
}

U_BOOT_CMD(
   env_cus_load ,    CONFIG_SYS_MAXARGS,    1,     do_env_cus_load,
	"env_cus_load   - load customize environment settings\n",
	"    -  \n"
);
