# SPDX-License-Identifier: (GPL-2.0-only OR BSD-3-Clause)
#
# Copyright (c) 2023 MediaTek Inc.
#

UBOOTINCLUDE += -I$(srctree)/Customization/$(CUSTOMER)/pnl_cust/include/ \
                -I$(srctree)/Mediatek-internal/drivers/driver/demura/base/ \
                -I$(srctree)/Mediatek-internal/impl/panel/

obj-y += src/mtk_pnl_cust.o
