# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2014 Google, Inc
#


INC_DIR += coda/
#INC_DIR += hal_common/
#INC_DIR += hal_v006/
UBOOTINCLUDE += -I$(srctree)/Mediatek-internal/drivers/include/
#UBOOTINCLUDE += -I$(srctree)/drivers/video/mtk-dtv/coda/

obj-y += mtk_pnl_utility.o
obj-y += mtk_pnl_autodownload.o
obj-y += mtk_tcon_common.o
obj-y += mtk_tcon_dga.o
obj-y += mtk_tcon_od.o
obj-y += mtk_tcon_lineod.o
obj-y += mtk_tcon_vac.o
obj-y += mtk_tcon_out_if.o
obj-y += mtk_pnl_out_if.o
obj-y += mtk_pnl_out_if_v006.o
obj-y += mtk_pnl_clk_ctrl.o
obj-y += mtk_pnl_clk_ctrl_v006.o
obj-y += mtk_tv_pnl.o
obj-y += mtk_tv_ldm.o

