# SPDX-License-Identifier:	GPL-2.0

include $(TOPDIR)/config.mk

ccflags-y += -I$(srctree)/include/linux
ccflags-y += -I$(srctree)/Mediatek-internal/drivers/include
ccflags-y += -I$(srctree)/Mediatek-internal/drivers/include/chip

obj-y += mt5896_rfb.o
obj-y += setup.o
