# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

UBOOTINCLUDE += -I$(srctree)/Mediatek-internal/impl/romtblo/


obj-y			+= mtk-dtv-mmc.o
obj-y			+= eMMC_hal.o
obj-y			+= eMMC_hal_atop.o
obj-y			+= eMMC_hal_speed.o
obj-y			+= eMMC_ip_verify.o
obj-y			+= eMMC_platform.o
obj-y			+= eMMC_utl.o
obj-y			+= eMMC_prg.o
obj-y			+= eMMC_RPMB.o
obj-y			+= FDE_hal.o
