# SPDX-License-Identifier: (GPL-2.0-only OR BSD-3-Clause)
#
# Copyright (c) 2023 MediaTek Inc.
#

UBOOTINCLUDE += -I$(srctree)/Mediatek-internal/include/ \
				-I$(srctree)/Mediatek-internal/impl/romtblo/

obj-y += ./romtblo_impl.o
