/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-3-Clause) */
/*
 * Copyright (c) 2023 MediaTek Inc.
 */

#ifndef _VOC_IMPL_HEADER_
#define _VOC_IMPL_HEADER_

enum voice_cmd_t {
	VOICE_CMD_DATA_MOVING_ENABLE = 0,
	VOICE_CMD_DATA_MOVING_CONFIG,
	VOICE_CMD_DATA_MOVING_NOTIFY,
	VOICE_CMD_DATA_MOVING_STATUS,
	VOICE_CMD_WAKEUP_ENABLE,
	VOICE_CMD_WAKEUP_CONFIG,
	VOICE_CMD_PREPROCESS_ENABLE,
	VOICE_CMD_PREPROCESS_CONFIG,
	VOICE_CMD_SIGEN_ENABLE,
	VOICE_CMD_MIC_GAIN,
	VOICE_CMD_HPF_STAGE,
	VOICE_CMD_HPF_CONFIG,
	VOICE_CMD_RESET,
	VOICE_CMD_SOUND_MODEL_UPDATE,
	VOICE_CMD_HOTWORD_VERSION,
	VOICE_CMD_HOTWORD_DETECTED,
	VOICE_CMD_HOTWORD_IDENTIFIER,
	VOICE_CMD_SLT_TEST,
	VOICE_CMD_TIMESTAMP_NOTIFY,
	VOICE_CMD_SEAMLESS,
	VOICE_CMD_STATUS_UPDATE,
	VOICE_CMD_MIC_MUTE_ENABLE,
	VOICE_CMD_MIC_SWITCH,
	VOICE_CMD_UBOOT_WAKEUP_ENABLE,
	VOICE_CMD_MAX,
};

int mtk_voc_get_value(void);
int mtk_voc_set_value(struct voc_env_info voc_info);
int mtk_voc_standby(struct voc_env_info voc_info);
#endif /* _VOC_IMPL_HEADER_ */

