
static char TEXT_IP_TMO_SOURCE_SETTING_Main[] = "TMO_SOURCE_SETTING";
static char TEXT_IP_TMO_TARGET_SETTING_Main[] = "TMO_TARGET_SETTING";
static char TEXT_IP_TMO_Option_Main[] = "TMO_Option";
static char TEXT_IP_NFXTest_SETTING_Main[] = "NFXTest_SETTING";
static char TEXT_IP_SWDR_SETTING_Main[] = "SWDR_SETTING";
static char TEXT_IP_UCD_SETTING_Main[] = "UCD_SETTING";
static char TEXT_IP_DLC_SETTING_Main[] = "DLC_SETTING";
static char TEXT_IP_AVC_SETTING_Main[] = "AVC_SETTING";
static char TEXT_IP_CFD_Control_Point_EN_Main[] = "CFD_Control_Point_EN";
static char TEXT_IP_CFD_Control_Point_2_Main[] = "CFD_Control_Point_2";
static char TEXT_IP_CFD_Control_Point_3_Main[] = "CFD_Control_Point_3";
static char TEXT_IP_Pre_SDR_IP_Main[] = "Pre_SDR_IP";
static char TEXT_IP_HDR_IP_Main[] = "HDR_IP";
static char TEXT_IP_Post_SDR_IP_Main[] = "Post_SDR_IP";


char* PQ_IP_Text_TMO_Main[] =
{
TEXT_IP_TMO_SOURCE_SETTING_Main,
TEXT_IP_TMO_TARGET_SETTING_Main,
TEXT_IP_TMO_Option_Main,
TEXT_IP_NFXTest_SETTING_Main,
TEXT_IP_SWDR_SETTING_Main,
TEXT_IP_UCD_SETTING_Main,
TEXT_IP_DLC_SETTING_Main,
TEXT_IP_AVC_SETTING_Main,
TEXT_IP_CFD_Control_Point_EN_Main,
TEXT_IP_CFD_Control_Point_2_Main,
TEXT_IP_CFD_Control_Point_3_Main,
TEXT_IP_Pre_SDR_IP_Main,
TEXT_IP_HDR_IP_Main,
TEXT_IP_Post_SDR_IP_Main,
};

char PQ_IPTAB_TMO_SOURCE_SETTING_OFF_Text_Main[] = "OFF";
char PQ_IPTAB_TMO_SOURCE_SETTING_RESERVED0_Text_Main[] = "RESERVED0";
char PQ_IPTAB_TMO_SOURCE_SETTING_BT709_Text_Main[] = "BT709";
char PQ_IPTAB_TMO_SOURCE_SETTING_UNSPECIFIED_Text_Main[] = "UNSPECIFIED";
char PQ_IPTAB_TMO_SOURCE_SETTING_RESERVED3_Text_Main[] = "RESERVED3";
char PQ_IPTAB_TMO_SOURCE_SETTING_GAMMA2P2_Text_Main[] = "GAMMA2P2";
char PQ_IPTAB_TMO_SOURCE_SETTING_GAMMA2P8_Text_Main[] = "GAMMA2P8";
char PQ_IPTAB_TMO_SOURCE_SETTING_BT601525_601625_Text_Main[] = "BT601525_601625";
char PQ_IPTAB_TMO_SOURCE_SETTING_SMPTE240M_Text_Main[] = "SMPTE240M";
char PQ_IPTAB_TMO_SOURCE_SETTING_LINEAR_Text_Main[] = "LINEAR";
char PQ_IPTAB_TMO_SOURCE_SETTING_LOG0_Text_Main[] = "LOG0";
char PQ_IPTAB_TMO_SOURCE_SETTING_LOG1_Text_Main[] = "LOG1";
char PQ_IPTAB_TMO_SOURCE_SETTING_XVYCC_Text_Main[] = "XVYCC";
char PQ_IPTAB_TMO_SOURCE_SETTING_BT1361_Text_Main[] = "BT1361";
char PQ_IPTAB_TMO_SOURCE_SETTING_SRGB_SYCC_Text_Main[] = "SRGB_SYCC";
char PQ_IPTAB_TMO_SOURCE_SETTING_BT2020NCL_Text_Main[] = "BT2020NCL";
char PQ_IPTAB_TMO_SOURCE_SETTING_BT2020CL_Text_Main[] = "BT2020CL";
char PQ_IPTAB_TMO_SOURCE_SETTING_SMPTE2084_Text_Main[] = "SMPTE2084";
char PQ_IPTAB_TMO_SOURCE_SETTING_SMPTE428_Text_Main[] = "SMPTE428";
char PQ_IPTAB_TMO_SOURCE_SETTING_HLG_Text_Main[] = "HLG";
char PQ_IPTAB_TMO_SOURCE_SETTING_BT1886_Text_Main[] = "BT1886";
char PQ_IPTAB_TMO_SOURCE_SETTING_DOLBYMETA_Text_Main[] = "DOLBYMETA";
char PQ_IPTAB_TMO_SOURCE_SETTING_ADOBERGB_Text_Main[] = "ADOBERGB";
char PQ_IPTAB_TMO_SOURCE_SETTING_HDR_Text_Main[] = "HDR";
char PQ_IPTAB_TMO_SOURCE_SETTING_MTK_QA_INX_28_160nit_Text_Main[] = "MTK_QA_INX_28_160nit";
char PQ_IPTAB_TMO_SOURCE_SETTING_MTK_QA_AUO_32_Text_Main[] = "MTK_QA_AUO_32";
char PQ_IPTAB_TMO_TARGET_SETTING_OFF_Text_Main[] = "OFF";
char PQ_IPTAB_TMO_TARGET_SETTING_RESERVED0_H_Text_Main[] = "RESERVED0_H";
char PQ_IPTAB_TMO_TARGET_SETTING_BT709_H_Text_Main[] = "BT709_H";
char PQ_IPTAB_TMO_TARGET_SETTING_UNSPECIFIED_H_Text_Main[] = "UNSPECIFIED_H";
char PQ_IPTAB_TMO_TARGET_SETTING_RESERVED3_H_Text_Main[] = "RESERVED3_H";
char PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P2_H_Text_Main[] = "GAMMA2P2_H";
char PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P8_H_Text_Main[] = "GAMMA2P8_H";
char PQ_IPTAB_TMO_TARGET_SETTING_BT601525_601625_H_Text_Main[] = "BT601525_601625_H";
char PQ_IPTAB_TMO_TARGET_SETTING_SMPTE240M_H_Text_Main[] = "SMPTE240M_H";
char PQ_IPTAB_TMO_TARGET_SETTING_LINEAR_H_Text_Main[] = "LINEAR_H";
char PQ_IPTAB_TMO_TARGET_SETTING_LOG0_H_Text_Main[] = "LOG0_H";
char PQ_IPTAB_TMO_TARGET_SETTING_LOG1_H_Text_Main[] = "LOG1_H";
char PQ_IPTAB_TMO_TARGET_SETTING_XVYCC_H_Text_Main[] = "XVYCC_H";
char PQ_IPTAB_TMO_TARGET_SETTING_BT1361_H_Text_Main[] = "BT1361_H";
char PQ_IPTAB_TMO_TARGET_SETTING_SRGB_SYCC_H_Text_Main[] = "SRGB_SYCC_H";
char PQ_IPTAB_TMO_TARGET_SETTING_BT2020NCL_H_Text_Main[] = "BT2020NCL_H";
char PQ_IPTAB_TMO_TARGET_SETTING_BT2020CL_H_Text_Main[] = "BT2020CL_H";
char PQ_IPTAB_TMO_TARGET_SETTING_SMPTE2084_H_Text_Main[] = "SMPTE2084_H";
char PQ_IPTAB_TMO_TARGET_SETTING_SMPTE428_H_Text_Main[] = "SMPTE428_H";
char PQ_IPTAB_TMO_TARGET_SETTING_HLG_H_Text_Main[] = "HLG_H";
char PQ_IPTAB_TMO_TARGET_SETTING_BT1886_H_Text_Main[] = "BT1886_H";
char PQ_IPTAB_TMO_TARGET_SETTING_DOLBYMETA_H_Text_Main[] = "DOLBYMETA_H";
char PQ_IPTAB_TMO_TARGET_SETTING_ADOBERGB_H_Text_Main[] = "ADOBERGB_H";
char PQ_IPTAB_TMO_TARGET_SETTING_RESERVED0_M_Text_Main[] = "RESERVED0_M";
char PQ_IPTAB_TMO_TARGET_SETTING_BT709_M_Text_Main[] = "BT709_M";
char PQ_IPTAB_TMO_TARGET_SETTING_UNSPECIFIED_M_Text_Main[] = "UNSPECIFIED_M";
char PQ_IPTAB_TMO_TARGET_SETTING_RESERVED3_M_Text_Main[] = "RESERVED3_M";
char PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P2_M_Text_Main[] = "GAMMA2P2_M";
char PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P8_M_Text_Main[] = "GAMMA2P8_M";
char PQ_IPTAB_TMO_TARGET_SETTING_BT601525_601625_M_Text_Main[] = "BT601525_601625_M";
char PQ_IPTAB_TMO_TARGET_SETTING_SMPTE240M_M_Text_Main[] = "SMPTE240M_M";
char PQ_IPTAB_TMO_TARGET_SETTING_LINEAR_M_Text_Main[] = "LINEAR_M";
char PQ_IPTAB_TMO_TARGET_SETTING_LOG0_M_Text_Main[] = "LOG0_M";
char PQ_IPTAB_TMO_TARGET_SETTING_LOG1_M_Text_Main[] = "LOG1_M";
char PQ_IPTAB_TMO_TARGET_SETTING_XVYCC_M_Text_Main[] = "XVYCC_M";
char PQ_IPTAB_TMO_TARGET_SETTING_BT1361_M_Text_Main[] = "BT1361_M";
char PQ_IPTAB_TMO_TARGET_SETTING_SRGB_SYCC_M_Text_Main[] = "SRGB_SYCC_M";
char PQ_IPTAB_TMO_TARGET_SETTING_BT2020NCL_M_Text_Main[] = "BT2020NCL_M";
char PQ_IPTAB_TMO_TARGET_SETTING_BT2020CL_M_Text_Main[] = "BT2020CL_M";
char PQ_IPTAB_TMO_TARGET_SETTING_SMPTE2084_M_Text_Main[] = "SMPTE2084_M";
char PQ_IPTAB_TMO_TARGET_SETTING_SMPTE428_M_Text_Main[] = "SMPTE428_M";
char PQ_IPTAB_TMO_TARGET_SETTING_HLG_M_Text_Main[] = "HLG_M";
char PQ_IPTAB_TMO_TARGET_SETTING_BT1886_M_Text_Main[] = "BT1886_M";
char PQ_IPTAB_TMO_TARGET_SETTING_DOLBYMETA_M_Text_Main[] = "DOLBYMETA_M";
char PQ_IPTAB_TMO_TARGET_SETTING_ADOBERGB_M_Text_Main[] = "ADOBERGB_M";
char PQ_IPTAB_TMO_TARGET_SETTING_RESERVED0_L_Text_Main[] = "RESERVED0_L";
char PQ_IPTAB_TMO_TARGET_SETTING_BT709_L_Text_Main[] = "BT709_L";
char PQ_IPTAB_TMO_TARGET_SETTING_UNSPECIFIED_L_Text_Main[] = "UNSPECIFIED_L";
char PQ_IPTAB_TMO_TARGET_SETTING_RESERVED3_L_Text_Main[] = "RESERVED3_L";
char PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P2_L_Text_Main[] = "GAMMA2P2_L";
char PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P8_L_Text_Main[] = "GAMMA2P8_L";
char PQ_IPTAB_TMO_TARGET_SETTING_BT601525_601625_L_Text_Main[] = "BT601525_601625_L";
char PQ_IPTAB_TMO_TARGET_SETTING_SMPTE240M_L_Text_Main[] = "SMPTE240M_L";
char PQ_IPTAB_TMO_TARGET_SETTING_LINEAR_L_Text_Main[] = "LINEAR_L";
char PQ_IPTAB_TMO_TARGET_SETTING_LOG0_L_Text_Main[] = "LOG0_L";
char PQ_IPTAB_TMO_TARGET_SETTING_LOG1_L_Text_Main[] = "LOG1_L";
char PQ_IPTAB_TMO_TARGET_SETTING_XVYCC_L_Text_Main[] = "XVYCC_L";
char PQ_IPTAB_TMO_TARGET_SETTING_BT1361_L_Text_Main[] = "BT1361_L";
char PQ_IPTAB_TMO_TARGET_SETTING_SRGB_SYCC_L_Text_Main[] = "SRGB_SYCC_L";
char PQ_IPTAB_TMO_TARGET_SETTING_BT2020NCL_L_Text_Main[] = "BT2020NCL_L";
char PQ_IPTAB_TMO_TARGET_SETTING_BT2020CL_L_Text_Main[] = "BT2020CL_L";
char PQ_IPTAB_TMO_TARGET_SETTING_SMPTE2084_L_Text_Main[] = "SMPTE2084_L";
char PQ_IPTAB_TMO_TARGET_SETTING_SMPTE428_L_Text_Main[] = "SMPTE428_L";
char PQ_IPTAB_TMO_TARGET_SETTING_HLG_L_Text_Main[] = "HLG_L";
char PQ_IPTAB_TMO_TARGET_SETTING_BT1886_L_Text_Main[] = "BT1886_L";
char PQ_IPTAB_TMO_TARGET_SETTING_DOLBYMETA_L_Text_Main[] = "DOLBYMETA_L";
char PQ_IPTAB_TMO_TARGET_SETTING_ADOBERGB_L_Text_Main[] = "ADOBERGB_L";
char PQ_IPTAB_TMO_TARGET_SETTING_HDR_Text_Main[] = "HDR";
char PQ_IPTAB_TMO_TARGET_SETTING_MTK_QA_INX_28_160nit_Text_Main[] = "MTK_QA_INX_28_160nit";
char PQ_IPTAB_TMO_TARGET_SETTING_MTK_QA_AUO_32_Text_Main[] = "MTK_QA_AUO_32";
char PQ_IPTAB_TMO_Option_OFF_Text_Main[] = "OFF";
char PQ_IPTAB_TMO_Option_RESERVED0_H_Text_Main[] = "RESERVED0_H";
char PQ_IPTAB_TMO_Option_BT709_H_Text_Main[] = "BT709_H";
char PQ_IPTAB_TMO_Option_UNSPECIFIED_H_Text_Main[] = "UNSPECIFIED_H";
char PQ_IPTAB_TMO_Option_RESERVED3_H_Text_Main[] = "RESERVED3_H";
char PQ_IPTAB_TMO_Option_GAMMA2P2_H_Text_Main[] = "GAMMA2P2_H";
char PQ_IPTAB_TMO_Option_GAMMA2P8_H_Text_Main[] = "GAMMA2P8_H";
char PQ_IPTAB_TMO_Option_BT601525_601625_H_Text_Main[] = "BT601525_601625_H";
char PQ_IPTAB_TMO_Option_SMPTE240M_H_Text_Main[] = "SMPTE240M_H";
char PQ_IPTAB_TMO_Option_LINEAR_H_Text_Main[] = "LINEAR_H";
char PQ_IPTAB_TMO_Option_LOG0_H_Text_Main[] = "LOG0_H";
char PQ_IPTAB_TMO_Option_LOG1_H_Text_Main[] = "LOG1_H";
char PQ_IPTAB_TMO_Option_XVYCC_H_Text_Main[] = "XVYCC_H";
char PQ_IPTAB_TMO_Option_BT1361_H_Text_Main[] = "BT1361_H";
char PQ_IPTAB_TMO_Option_SRGB_SYCC_H_Text_Main[] = "SRGB_SYCC_H";
char PQ_IPTAB_TMO_Option_BT2020NCL_H_Text_Main[] = "BT2020NCL_H";
char PQ_IPTAB_TMO_Option_BT2020CL_H_Text_Main[] = "BT2020CL_H";
char PQ_IPTAB_TMO_Option_SMPTE2084_H_Text_Main[] = "SMPTE2084_H";
char PQ_IPTAB_TMO_Option_SMPTE428_H_Text_Main[] = "SMPTE428_H";
char PQ_IPTAB_TMO_Option_HLG_H_Text_Main[] = "HLG_H";
char PQ_IPTAB_TMO_Option_BT1886_H_Text_Main[] = "BT1886_H";
char PQ_IPTAB_TMO_Option_DOLBYMETA_H_Text_Main[] = "DOLBYMETA_H";
char PQ_IPTAB_TMO_Option_ADOBERGB_H_Text_Main[] = "ADOBERGB_H";
char PQ_IPTAB_TMO_Option_RESERVED0_M_Text_Main[] = "RESERVED0_M";
char PQ_IPTAB_TMO_Option_BT709_M_Text_Main[] = "BT709_M";
char PQ_IPTAB_TMO_Option_UNSPECIFIED_M_Text_Main[] = "UNSPECIFIED_M";
char PQ_IPTAB_TMO_Option_RESERVED3_M_Text_Main[] = "RESERVED3_M";
char PQ_IPTAB_TMO_Option_GAMMA2P2_M_Text_Main[] = "GAMMA2P2_M";
char PQ_IPTAB_TMO_Option_GAMMA2P8_M_Text_Main[] = "GAMMA2P8_M";
char PQ_IPTAB_TMO_Option_BT601525_601625_M_Text_Main[] = "BT601525_601625_M";
char PQ_IPTAB_TMO_Option_SMPTE240M_M_Text_Main[] = "SMPTE240M_M";
char PQ_IPTAB_TMO_Option_LINEAR_M_Text_Main[] = "LINEAR_M";
char PQ_IPTAB_TMO_Option_LOG0_M_Text_Main[] = "LOG0_M";
char PQ_IPTAB_TMO_Option_LOG1_M_Text_Main[] = "LOG1_M";
char PQ_IPTAB_TMO_Option_XVYCC_M_Text_Main[] = "XVYCC_M";
char PQ_IPTAB_TMO_Option_BT1361_M_Text_Main[] = "BT1361_M";
char PQ_IPTAB_TMO_Option_SRGB_SYCC_M_Text_Main[] = "SRGB_SYCC_M";
char PQ_IPTAB_TMO_Option_BT2020NCL_M_Text_Main[] = "BT2020NCL_M";
char PQ_IPTAB_TMO_Option_BT2020CL_M_Text_Main[] = "BT2020CL_M";
char PQ_IPTAB_TMO_Option_SMPTE2084_M_Text_Main[] = "SMPTE2084_M";
char PQ_IPTAB_TMO_Option_SMPTE428_M_Text_Main[] = "SMPTE428_M";
char PQ_IPTAB_TMO_Option_HLG_M_Text_Main[] = "HLG_M";
char PQ_IPTAB_TMO_Option_BT1886_M_Text_Main[] = "BT1886_M";
char PQ_IPTAB_TMO_Option_DOLBYMETA_M_Text_Main[] = "DOLBYMETA_M";
char PQ_IPTAB_TMO_Option_ADOBERGB_M_Text_Main[] = "ADOBERGB_M";
char PQ_IPTAB_TMO_Option_RESERVED0_L_Text_Main[] = "RESERVED0_L";
char PQ_IPTAB_TMO_Option_BT709_L_Text_Main[] = "BT709_L";
char PQ_IPTAB_TMO_Option_UNSPECIFIED_L_Text_Main[] = "UNSPECIFIED_L";
char PQ_IPTAB_TMO_Option_RESERVED3_L_Text_Main[] = "RESERVED3_L";
char PQ_IPTAB_TMO_Option_GAMMA2P2_L_Text_Main[] = "GAMMA2P2_L";
char PQ_IPTAB_TMO_Option_GAMMA2P8_L_Text_Main[] = "GAMMA2P8_L";
char PQ_IPTAB_TMO_Option_BT601525_601625_L_Text_Main[] = "BT601525_601625_L";
char PQ_IPTAB_TMO_Option_SMPTE240M_L_Text_Main[] = "SMPTE240M_L";
char PQ_IPTAB_TMO_Option_LINEAR_L_Text_Main[] = "LINEAR_L";
char PQ_IPTAB_TMO_Option_LOG0_L_Text_Main[] = "LOG0_L";
char PQ_IPTAB_TMO_Option_LOG1_L_Text_Main[] = "LOG1_L";
char PQ_IPTAB_TMO_Option_XVYCC_L_Text_Main[] = "XVYCC_L";
char PQ_IPTAB_TMO_Option_BT1361_L_Text_Main[] = "BT1361_L";
char PQ_IPTAB_TMO_Option_SRGB_SYCC_L_Text_Main[] = "SRGB_SYCC_L";
char PQ_IPTAB_TMO_Option_BT2020NCL_L_Text_Main[] = "BT2020NCL_L";
char PQ_IPTAB_TMO_Option_BT2020CL_L_Text_Main[] = "BT2020CL_L";
char PQ_IPTAB_TMO_Option_SMPTE2084_L_Text_Main[] = "SMPTE2084_L";
char PQ_IPTAB_TMO_Option_SMPTE428_L_Text_Main[] = "SMPTE428_L";
char PQ_IPTAB_TMO_Option_HLG_L_Text_Main[] = "HLG_L";
char PQ_IPTAB_TMO_Option_BT1886_L_Text_Main[] = "BT1886_L";
char PQ_IPTAB_TMO_Option_DOLBYMETA_L_Text_Main[] = "DOLBYMETA_L";
char PQ_IPTAB_TMO_Option_ADOBERGB_L_Text_Main[] = "ADOBERGB_L";
char PQ_IPTAB_NFXTest_SETTING_OFF_Text_Main[] = "OFF";
char PQ_IPTAB_NFXTest_SETTING_NFX_105_Text_Main[] = "NFX_105";
char PQ_IPTAB_NFXTest_SETTING_NFX_422_Text_Main[] = "NFX_422";
char PQ_IPTAB_NFXTest_SETTING_NFX_422_350_Text_Main[] = "NFX_422_350";
char PQ_IPTAB_NFXTest_SETTING_NFX_422_350_noDLC_Text_Main[] = "NFX_422_350_noDLC";
char PQ_IPTAB_SWDR_SETTING_OFF_Text_Main[] = "OFF";
char PQ_IPTAB_SWDR_SETTING_RESERVED_H_Text_Main[] = "RESERVED_H";
char PQ_IPTAB_SWDR_SETTING_DR_H_Text_Main[] = "DR_H";
char PQ_IPTAB_SWDR_SETTING_SWDR_H_Text_Main[] = "SWDR_H";
char PQ_IPTAB_SWDR_SETTING_RESERVED_M_Text_Main[] = "RESERVED_M";
char PQ_IPTAB_SWDR_SETTING_DR_M_Text_Main[] = "DR_M";
char PQ_IPTAB_SWDR_SETTING_SWDR_M_Text_Main[] = "SWDR_M";
char PQ_IPTAB_SWDR_SETTING_RESERVED_L_Text_Main[] = "RESERVED_L";
char PQ_IPTAB_SWDR_SETTING_DR_L_Text_Main[] = "DR_L";
char PQ_IPTAB_SWDR_SETTING_SWDR_L_Text_Main[] = "SWDR_L";
char PQ_IPTAB_SWDR_SETTING_AIPQ_DR_M_Text_Main[] = "AIPQ_DR_M";
char PQ_IPTAB_UCD_SETTING_OFF_Text_Main[] = "OFF";
char PQ_IPTAB_UCD_SETTING_LOW_Text_Main[] = "LOW";
char PQ_IPTAB_UCD_SETTING_MID_Text_Main[] = "MID";
char PQ_IPTAB_UCD_SETTING_HIGH_Text_Main[] = "HIGH";
char PQ_IPTAB_DLC_SETTING_Default_Text_Main[] = "Default";
char PQ_IPTAB_DLC_SETTING_High_Text_Main[] = "High";
char PQ_IPTAB_DLC_SETTING_Mid_Text_Main[] = "Mid";
char PQ_IPTAB_DLC_SETTING_Low_Text_Main[] = "Low";
char PQ_IPTAB_DLC_SETTING_High_HDR_Text_Main[] = "High_HDR";
char PQ_IPTAB_DLC_SETTING_Mid_HDR_Text_Main[] = "Mid_HDR";
char PQ_IPTAB_DLC_SETTING_Low_HDR_Text_Main[] = "Low_HDR";
char PQ_IPTAB_DLC_SETTING_High_HLG_Text_Main[] = "High_HLG";
char PQ_IPTAB_DLC_SETTING_Mid_HLG_Text_Main[] = "Mid_HLG";
char PQ_IPTAB_DLC_SETTING_Low_HLG_Text_Main[] = "Low_HLG";
char PQ_IPTAB_DLC_SETTING_HDR_Demo0912_Text_Main[] = "HDR_Demo0912";
char PQ_IPTAB_DLC_SETTING_Mid_Demo_Text_Main[] = "Mid_Demo";
char PQ_IPTAB_AVC_SETTING_OFF_Text_Main[] = "OFF";
char PQ_IPTAB_AVC_SETTING_LINEAR_Text_Main[] = "LINEAR";
char PQ_IPTAB_AVC_SETTING_NORMAL_Text_Main[] = "NORMAL";
char PQ_IPTAB_AVC_SETTING_HIGH_Text_Main[] = "HIGH";
char PQ_IPTAB_CFD_Control_Point_EN_OFF_Text_Main[] = "OFF";
char PQ_IPTAB_CFD_Control_Point_EN_All_ON_Text_Main[] = "All_ON";
char PQ_IPTAB_CFD_Control_Point_EN_Gamut_on_Text_Main[] = "Gamut_on";
char PQ_IPTAB_CFD_Control_Point_2_OFF_Text_Main[] = "OFF";
char PQ_IPTAB_CFD_Control_Point_2_SDR_Text_Main[] = "SDR";
char PQ_IPTAB_CFD_Control_Point_2_HDR_Text_Main[] = "HDR";
char PQ_IPTAB_CFD_Control_Point_2_DOLBY_Text_Main[] = "DOLBY";
char PQ_IPTAB_CFD_Control_Point_3_OFF_Text_Main[] = "OFF";
char PQ_IPTAB_CFD_Control_Point_3_SDR_Text_Main[] = "SDR";
char PQ_IPTAB_CFD_Control_Point_3_HDR_Text_Main[] = "HDR";
char PQ_IPTAB_CFD_Control_Point_3_Panel_Out_Text_Main[] = "Panel_Out";
char PQ_IPTAB_Pre_SDR_IP_OFF_Text_Main[] = "OFF";
char PQ_IPTAB_Pre_SDR_IP_default_Text_Main[] = "default";
char PQ_IPTAB_Pre_SDR_IP_Customer1_Text_Main[] = "Customer1";
char PQ_IPTAB_HDR_IP_OFF_Text_Main[] = "OFF";
char PQ_IPTAB_HDR_IP_default_Text_Main[] = "default";
char PQ_IPTAB_HDR_IP_Customer1_Text_Main[] = "Customer1";
char PQ_IPTAB_Post_SDR_IP_OFF_Text_Main[] = "OFF";
char PQ_IPTAB_Post_SDR_IP_default_Text_Main[] = "default";
char PQ_IPTAB_Post_SDR_IP_Customer1_Text_Main[] = "Customer1";
char PQ_IPTAB_Post_SDR_IP_MI_3_Text_Main[] = "MI_3";

char* PQ_IP_TMO_SOURCE_SETTING_Text_Main[] =
{
PQ_IPTAB_TMO_SOURCE_SETTING_OFF_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_RESERVED0_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_BT709_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_UNSPECIFIED_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_RESERVED3_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_GAMMA2P2_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_GAMMA2P8_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_BT601525_601625_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_SMPTE240M_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_LINEAR_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_LOG0_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_LOG1_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_XVYCC_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_BT1361_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_SRGB_SYCC_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_BT2020NCL_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_BT2020CL_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_SMPTE2084_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_SMPTE428_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_HLG_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_BT1886_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_DOLBYMETA_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_ADOBERGB_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_HDR_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_MTK_QA_INX_28_160nit_Text_Main,
PQ_IPTAB_TMO_SOURCE_SETTING_MTK_QA_AUO_32_Text_Main,
};

char* PQ_IP_TMO_TARGET_SETTING_Text_Main[] =
{
PQ_IPTAB_TMO_TARGET_SETTING_OFF_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_RESERVED0_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_BT709_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_UNSPECIFIED_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_RESERVED3_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P2_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P8_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_BT601525_601625_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_SMPTE240M_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_LINEAR_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_LOG0_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_LOG1_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_XVYCC_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_BT1361_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_SRGB_SYCC_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_BT2020NCL_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_BT2020CL_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_SMPTE2084_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_SMPTE428_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_HLG_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_BT1886_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_DOLBYMETA_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_ADOBERGB_H_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_RESERVED0_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_BT709_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_UNSPECIFIED_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_RESERVED3_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P2_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P8_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_BT601525_601625_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_SMPTE240M_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_LINEAR_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_LOG0_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_LOG1_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_XVYCC_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_BT1361_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_SRGB_SYCC_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_BT2020NCL_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_BT2020CL_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_SMPTE2084_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_SMPTE428_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_HLG_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_BT1886_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_DOLBYMETA_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_ADOBERGB_M_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_RESERVED0_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_BT709_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_UNSPECIFIED_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_RESERVED3_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P2_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P8_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_BT601525_601625_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_SMPTE240M_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_LINEAR_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_LOG0_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_LOG1_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_XVYCC_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_BT1361_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_SRGB_SYCC_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_BT2020NCL_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_BT2020CL_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_SMPTE2084_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_SMPTE428_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_HLG_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_BT1886_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_DOLBYMETA_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_ADOBERGB_L_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_HDR_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_MTK_QA_INX_28_160nit_Text_Main,
PQ_IPTAB_TMO_TARGET_SETTING_MTK_QA_AUO_32_Text_Main,
};

char* PQ_IP_TMO_Option_Text_Main[] =
{
PQ_IPTAB_TMO_Option_OFF_Text_Main,
PQ_IPTAB_TMO_Option_RESERVED0_H_Text_Main,
PQ_IPTAB_TMO_Option_BT709_H_Text_Main,
PQ_IPTAB_TMO_Option_UNSPECIFIED_H_Text_Main,
PQ_IPTAB_TMO_Option_RESERVED3_H_Text_Main,
PQ_IPTAB_TMO_Option_GAMMA2P2_H_Text_Main,
PQ_IPTAB_TMO_Option_GAMMA2P8_H_Text_Main,
PQ_IPTAB_TMO_Option_BT601525_601625_H_Text_Main,
PQ_IPTAB_TMO_Option_SMPTE240M_H_Text_Main,
PQ_IPTAB_TMO_Option_LINEAR_H_Text_Main,
PQ_IPTAB_TMO_Option_LOG0_H_Text_Main,
PQ_IPTAB_TMO_Option_LOG1_H_Text_Main,
PQ_IPTAB_TMO_Option_XVYCC_H_Text_Main,
PQ_IPTAB_TMO_Option_BT1361_H_Text_Main,
PQ_IPTAB_TMO_Option_SRGB_SYCC_H_Text_Main,
PQ_IPTAB_TMO_Option_BT2020NCL_H_Text_Main,
PQ_IPTAB_TMO_Option_BT2020CL_H_Text_Main,
PQ_IPTAB_TMO_Option_SMPTE2084_H_Text_Main,
PQ_IPTAB_TMO_Option_SMPTE428_H_Text_Main,
PQ_IPTAB_TMO_Option_HLG_H_Text_Main,
PQ_IPTAB_TMO_Option_BT1886_H_Text_Main,
PQ_IPTAB_TMO_Option_DOLBYMETA_H_Text_Main,
PQ_IPTAB_TMO_Option_ADOBERGB_H_Text_Main,
PQ_IPTAB_TMO_Option_RESERVED0_M_Text_Main,
PQ_IPTAB_TMO_Option_BT709_M_Text_Main,
PQ_IPTAB_TMO_Option_UNSPECIFIED_M_Text_Main,
PQ_IPTAB_TMO_Option_RESERVED3_M_Text_Main,
PQ_IPTAB_TMO_Option_GAMMA2P2_M_Text_Main,
PQ_IPTAB_TMO_Option_GAMMA2P8_M_Text_Main,
PQ_IPTAB_TMO_Option_BT601525_601625_M_Text_Main,
PQ_IPTAB_TMO_Option_SMPTE240M_M_Text_Main,
PQ_IPTAB_TMO_Option_LINEAR_M_Text_Main,
PQ_IPTAB_TMO_Option_LOG0_M_Text_Main,
PQ_IPTAB_TMO_Option_LOG1_M_Text_Main,
PQ_IPTAB_TMO_Option_XVYCC_M_Text_Main,
PQ_IPTAB_TMO_Option_BT1361_M_Text_Main,
PQ_IPTAB_TMO_Option_SRGB_SYCC_M_Text_Main,
PQ_IPTAB_TMO_Option_BT2020NCL_M_Text_Main,
PQ_IPTAB_TMO_Option_BT2020CL_M_Text_Main,
PQ_IPTAB_TMO_Option_SMPTE2084_M_Text_Main,
PQ_IPTAB_TMO_Option_SMPTE428_M_Text_Main,
PQ_IPTAB_TMO_Option_HLG_M_Text_Main,
PQ_IPTAB_TMO_Option_BT1886_M_Text_Main,
PQ_IPTAB_TMO_Option_DOLBYMETA_M_Text_Main,
PQ_IPTAB_TMO_Option_ADOBERGB_M_Text_Main,
PQ_IPTAB_TMO_Option_RESERVED0_L_Text_Main,
PQ_IPTAB_TMO_Option_BT709_L_Text_Main,
PQ_IPTAB_TMO_Option_UNSPECIFIED_L_Text_Main,
PQ_IPTAB_TMO_Option_RESERVED3_L_Text_Main,
PQ_IPTAB_TMO_Option_GAMMA2P2_L_Text_Main,
PQ_IPTAB_TMO_Option_GAMMA2P8_L_Text_Main,
PQ_IPTAB_TMO_Option_BT601525_601625_L_Text_Main,
PQ_IPTAB_TMO_Option_SMPTE240M_L_Text_Main,
PQ_IPTAB_TMO_Option_LINEAR_L_Text_Main,
PQ_IPTAB_TMO_Option_LOG0_L_Text_Main,
PQ_IPTAB_TMO_Option_LOG1_L_Text_Main,
PQ_IPTAB_TMO_Option_XVYCC_L_Text_Main,
PQ_IPTAB_TMO_Option_BT1361_L_Text_Main,
PQ_IPTAB_TMO_Option_SRGB_SYCC_L_Text_Main,
PQ_IPTAB_TMO_Option_BT2020NCL_L_Text_Main,
PQ_IPTAB_TMO_Option_BT2020CL_L_Text_Main,
PQ_IPTAB_TMO_Option_SMPTE2084_L_Text_Main,
PQ_IPTAB_TMO_Option_SMPTE428_L_Text_Main,
PQ_IPTAB_TMO_Option_HLG_L_Text_Main,
PQ_IPTAB_TMO_Option_BT1886_L_Text_Main,
PQ_IPTAB_TMO_Option_DOLBYMETA_L_Text_Main,
PQ_IPTAB_TMO_Option_ADOBERGB_L_Text_Main,
};

char* PQ_IP_NFXTest_SETTING_Text_Main[] =
{
PQ_IPTAB_NFXTest_SETTING_OFF_Text_Main,
PQ_IPTAB_NFXTest_SETTING_NFX_105_Text_Main,
PQ_IPTAB_NFXTest_SETTING_NFX_422_Text_Main,
PQ_IPTAB_NFXTest_SETTING_NFX_422_350_Text_Main,
PQ_IPTAB_NFXTest_SETTING_NFX_422_350_noDLC_Text_Main,
};

char* PQ_IP_SWDR_SETTING_Text_Main[] =
{
PQ_IPTAB_SWDR_SETTING_OFF_Text_Main,
PQ_IPTAB_SWDR_SETTING_RESERVED_H_Text_Main,
PQ_IPTAB_SWDR_SETTING_DR_H_Text_Main,
PQ_IPTAB_SWDR_SETTING_SWDR_H_Text_Main,
PQ_IPTAB_SWDR_SETTING_RESERVED_M_Text_Main,
PQ_IPTAB_SWDR_SETTING_DR_M_Text_Main,
PQ_IPTAB_SWDR_SETTING_SWDR_M_Text_Main,
PQ_IPTAB_SWDR_SETTING_RESERVED_L_Text_Main,
PQ_IPTAB_SWDR_SETTING_DR_L_Text_Main,
PQ_IPTAB_SWDR_SETTING_SWDR_L_Text_Main,
PQ_IPTAB_SWDR_SETTING_AIPQ_DR_M_Text_Main,
};

char* PQ_IP_UCD_SETTING_Text_Main[] =
{
PQ_IPTAB_UCD_SETTING_OFF_Text_Main,
PQ_IPTAB_UCD_SETTING_LOW_Text_Main,
PQ_IPTAB_UCD_SETTING_MID_Text_Main,
PQ_IPTAB_UCD_SETTING_HIGH_Text_Main,
};

char* PQ_IP_DLC_SETTING_Text_Main[] =
{
PQ_IPTAB_DLC_SETTING_Default_Text_Main,
PQ_IPTAB_DLC_SETTING_High_Text_Main,
PQ_IPTAB_DLC_SETTING_Mid_Text_Main,
PQ_IPTAB_DLC_SETTING_Low_Text_Main,
PQ_IPTAB_DLC_SETTING_High_HDR_Text_Main,
PQ_IPTAB_DLC_SETTING_Mid_HDR_Text_Main,
PQ_IPTAB_DLC_SETTING_Low_HDR_Text_Main,
PQ_IPTAB_DLC_SETTING_High_HLG_Text_Main,
PQ_IPTAB_DLC_SETTING_Mid_HLG_Text_Main,
PQ_IPTAB_DLC_SETTING_Low_HLG_Text_Main,
PQ_IPTAB_DLC_SETTING_HDR_Demo0912_Text_Main,
PQ_IPTAB_DLC_SETTING_Mid_Demo_Text_Main,
};

char* PQ_IP_AVC_SETTING_Text_Main[] =
{
PQ_IPTAB_AVC_SETTING_OFF_Text_Main,
PQ_IPTAB_AVC_SETTING_LINEAR_Text_Main,
PQ_IPTAB_AVC_SETTING_NORMAL_Text_Main,
PQ_IPTAB_AVC_SETTING_HIGH_Text_Main,
};

char* PQ_IP_CFD_Control_Point_EN_Text_Main[] =
{
PQ_IPTAB_CFD_Control_Point_EN_OFF_Text_Main,
PQ_IPTAB_CFD_Control_Point_EN_All_ON_Text_Main,
PQ_IPTAB_CFD_Control_Point_EN_Gamut_on_Text_Main,
};

char* PQ_IP_CFD_Control_Point_2_Text_Main[] =
{
PQ_IPTAB_CFD_Control_Point_2_OFF_Text_Main,
PQ_IPTAB_CFD_Control_Point_2_SDR_Text_Main,
PQ_IPTAB_CFD_Control_Point_2_HDR_Text_Main,
PQ_IPTAB_CFD_Control_Point_2_DOLBY_Text_Main,
};

char* PQ_IP_CFD_Control_Point_3_Text_Main[] =
{
PQ_IPTAB_CFD_Control_Point_3_OFF_Text_Main,
PQ_IPTAB_CFD_Control_Point_3_SDR_Text_Main,
PQ_IPTAB_CFD_Control_Point_3_HDR_Text_Main,
PQ_IPTAB_CFD_Control_Point_3_Panel_Out_Text_Main,
};

char* PQ_IP_Pre_SDR_IP_Text_Main[] =
{
PQ_IPTAB_Pre_SDR_IP_OFF_Text_Main,
PQ_IPTAB_Pre_SDR_IP_default_Text_Main,
PQ_IPTAB_Pre_SDR_IP_Customer1_Text_Main,
};

char* PQ_IP_HDR_IP_Text_Main[] =
{
PQ_IPTAB_HDR_IP_OFF_Text_Main,
PQ_IPTAB_HDR_IP_default_Text_Main,
PQ_IPTAB_HDR_IP_Customer1_Text_Main,
};

char* PQ_IP_Post_SDR_IP_Text_Main[] =
{
PQ_IPTAB_Post_SDR_IP_OFF_Text_Main,
PQ_IPTAB_Post_SDR_IP_default_Text_Main,
PQ_IPTAB_Post_SDR_IP_Customer1_Text_Main,
PQ_IPTAB_Post_SDR_IP_MI_3_Text_Main,
};

char** PQ_IPTAB_TEXT_TMO_Main[]=
{
PQ_IP_TMO_SOURCE_SETTING_Text_Main,
PQ_IP_TMO_TARGET_SETTING_Text_Main,
PQ_IP_TMO_Option_Text_Main,
PQ_IP_NFXTest_SETTING_Text_Main,
PQ_IP_SWDR_SETTING_Text_Main,
PQ_IP_UCD_SETTING_Text_Main,
PQ_IP_DLC_SETTING_Text_Main,
PQ_IP_AVC_SETTING_Text_Main,
PQ_IP_CFD_Control_Point_EN_Text_Main,
PQ_IP_CFD_Control_Point_2_Text_Main,
PQ_IP_CFD_Control_Point_3_Text_Main,
PQ_IP_Pre_SDR_IP_Text_Main,
PQ_IP_HDR_IP_Text_Main,
PQ_IP_Post_SDR_IP_Text_Main,
};

