#define PQ_HSDRule_ID_Main 0
#define PQ_HSDRule_IP_NUM_Main 2
#define PQ_HSDRule_NUM_Main 24

#define PQ_HSDRULE_PREV_SCALINGDOWN_INTERLACE_MAIN 1
#define PQ_HSDRULE_PREV_SCALINGDOWN_PROGRESSIVE_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_00X_YUV_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_00X_RGB_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_01X_YUV_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_01X_RGB_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_02X_YUV_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_02X_RGB_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_03X_YUV_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_03X_RGB_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_04X_YUV_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_04X_RGB_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_05X_YUV_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_05X_RGB_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_06X_YUV_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_06X_RGB_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_07X_YUV_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_07X_RGB_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_08X_YUV_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_08X_RGB_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_09X_YUV_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_09X_RGB_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_10X_YUV_MAIN 1
#define PQ_HSDRULE_SCALINGDOWN_10X_RGB_MAIN 1

typedef enum
{
PQ_HSDRule_PreV_ScalingDown_Interlace_Main,
PQ_HSDRule_PreV_ScalingDown_Progressive_Main,
PQ_HSDRule_ScalingDown_00x_YUV_Main,
PQ_HSDRule_ScalingDown_00x_RGB_Main,
PQ_HSDRule_ScalingDown_01x_YUV_Main,
PQ_HSDRule_ScalingDown_01x_RGB_Main,
PQ_HSDRule_ScalingDown_02x_YUV_Main,
PQ_HSDRule_ScalingDown_02x_RGB_Main,
PQ_HSDRule_ScalingDown_03x_YUV_Main,
PQ_HSDRule_ScalingDown_03x_RGB_Main,
PQ_HSDRule_ScalingDown_04x_YUV_Main,
PQ_HSDRule_ScalingDown_04x_RGB_Main,
PQ_HSDRule_ScalingDown_05x_YUV_Main,
PQ_HSDRule_ScalingDown_05x_RGB_Main,
PQ_HSDRule_ScalingDown_06x_YUV_Main,
PQ_HSDRule_ScalingDown_06x_RGB_Main,
PQ_HSDRule_ScalingDown_07x_YUV_Main,
PQ_HSDRule_ScalingDown_07x_RGB_Main,
PQ_HSDRule_ScalingDown_08x_YUV_Main,
PQ_HSDRule_ScalingDown_08x_RGB_Main,
PQ_HSDRule_ScalingDown_09x_YUV_Main,
PQ_HSDRule_ScalingDown_09x_RGB_Main,
PQ_HSDRule_ScalingDown_10x_YUV_Main,
PQ_HSDRule_ScalingDown_10x_RGB_Main,
}
MST_HSDRule_Index_Main;
extern U8 MST_HSDRule_IP_Index_Main[PQ_HSDRule_IP_NUM_Main];
extern U8 MST_HSDRule_Array_Main[PQ_HSDRule_NUM_Main][PQ_HSDRule_IP_NUM_Main];

