# SPDX-License-Identifier: (GPL-2.0-only OR BSD-3-Clause)
#
# Copyright (c) 2023 MediaTek Inc.
#

UBOOTINCLUDE += -I$(srctree)/Mediatek-internal/drivers/include/ \
                -I$(srctree)/Mediatek-internal/drivers/include/chip \
                -I$(srctree)/Mediatek-internal/impl/system/include/ \
                -I$(srctree)/Mediatek-internal/impl/upgrade/include/ \
                -I$(srctree)/Mediatek-internal/impl/partition/include/ \
                -I$(srctree)/Mediatek-internal/impl/one_package/include/ \
				-I$(srctree)/Mediatek-internal/secure/

obj-y += drivers/driver/
obj-y += impl/
obj-y += cmd/
obj-y += secure/
