# SPDX-License-Identifier: GPL-2.0+
#
# Copyright 2000-2008
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

obj-$(CONFIG_LD_BTMTK_USB) += ./src/LD_btmtk_usb.o
obj-$(CONFIG_LD_USBBT) += ./src/LD_usbbt.o
obj-$(CONFIG_LD_CUSMTKBT) += ./cmd/cmd_CusMtkBT.o

obj-y += ./src/LD_btmtk_usb.o
obj-y += ./src/LD_usbbt.o
obj-y += ./cmd/cmd_CusMtkBT.o

