# SPDX-License-Identifier: GPL-2.0
# Core
obj-$(CONFIG_ARCH_MEDIATEK) += clk-mtk.o

# SoC Drivers
obj-$(CONFIG_TARGET_MT7623) += clk-mt7623.o
obj-$(CONFIG_TARGET_MT7629) += clk-mt7629.o
obj-$(CONFIG_TARGET_MT5888) += clk-mt5888.o
obj-$(CONFIG_TARGET_MT5896) += clk-mt5896.o
