####################################################################
#######                    Makefile.ufbl                     #######
####################################################################

# UFBL
SRCTREE               := $(srctree)
OBJTREE               := $(objtree)
GET_LOCAL_DIR    = $(patsubst %/,%,$(dir $(word $(words $(MAKEFILE_LIST)),$(MAKEFILE_LIST))))
KBUILD_LOCAL_DIR_FUNC := $$(patsubst \%/,\%,$$(dir $$(word $$(words $$(MAKEFILE_LIST)),$$(MAKEFILE_LIST))))
KBUILD_LOCAL_DIR       = $(call KBUILD_LOCAL_DIR_FUNC)
TOPDIR  := $(shell cd $(srctree) && /bin/pwd)
#obj    := $(shell cd $(buildtree) && /bin/pwd)/
export SRCTREE OBJTREE GET_LOCAL_DIR KBUILD_LOCAL_DIR_FUNC KBUILD_LOCAL_DIR TOPDIR


UFBL_ENABLE     := yes
UFBL_PATH       := $(ANDROID_TOP)/bootable/bootloader/ufbl-features
UFBL_LIB_PATH   := $(UFBL_PATH)/features
UFBL_INC_PATH   := $(UFBL_PATH)/include
UFBL_PROJECT    := mtk_t61p

#USE_STDINT      := yes

export UFBL_ENABLE UFBL_PATH UFBL_PROJECT UFBL_LIB_PATH GET_LOCAL_DIR

IDME_HEADERS += \
	-I$(SRCTREE)/include/linux/ \
	-I$(SRCTREE)/drivers/mmc/mtk-dtv/ \
	-I$(SRCTREE)/Mediatek-internal/include/ \
	-I$(SRCTREE)/Mediatek-internal/impl/romtblo

export IDME_HEADERS

include $(UFBL_PATH)/build/ufbl_uboot.mk

UBOOTINCLUDE    += \
	-I$(UFBL_INC_PATH)


UFBL_LIBS_PATH := $(dir $(sort $(UFBL_LIBS)))
libs-y += $(UFBL_LIBS_PATH)
